export const MOVEMENT_OPTIONS = [
  { value: 'DOOR_TO_DOOR', label: 'movementTypes.DOOR_TO_DOOR' },
  { value: 'PORT_TO_DOOR', label: 'movementTypes.PORT_TO_DOOR' },
  { value: 'DOOR_TO_PORT', label: 'movementTypes.DOOR_TO_PORT' },
  { value: 'PORT_TO_PORT', label: 'movementTypes.PORT_TO_PORT' },
];

// export const COUNTRY_OPTIONS = [
//   { value: 'AF', label: 'Afghanistan' },
//   { value: 'AX', label: 'Åland Islands' },
//   { value: 'AL', label: 'Albania' },
//   { value: 'DZ', label: 'Algeria' },
//   { value: 'AS', label: 'American Samoa' },
//   { value: 'AD', label: 'Andorra' },
//   { value: 'AO', label: 'Angola' },
//   { value: 'AI', label: 'Anguilla' },
//   { value: 'AQ', label: 'Antarctica' },
//   { value: 'AG', label: 'Antigua and Barbuda' },
//   { value: 'AR', label: 'Argentina' },
//   { value: 'AM', label: 'Armenia' },
//   { value: 'AW', label: 'Aruba' },
//   { value: 'AU', label: 'Australia' },
//   { value: 'AT', label: 'Austria' },
//   { value: 'AZ', label: 'Azerbaijan' },
//   { value: 'BS', label: 'Bahamas' },
//   { value: 'BH', label: 'Bahrain' },
//   { value: 'BD', label: 'Bangladesh' },
//   { value: 'BB', label: 'Barbados' },
//   { value: 'BY', label: 'Belarus' },
//   { value: 'BE', label: 'Belgium' },
//   { value: 'BZ', label: 'Belize' },
//   { value: 'BJ', label: 'Benin' },
//   { value: 'BM', label: 'Bermuda' },
//   { value: 'BT', label: 'Bhutan' },
//   { value: 'BO', label: 'Bolivia' },
//   { value: 'BQ', label: 'Bonaire, Sint Eustatius and Saba' },
//   { value: 'BA', label: 'Bosnia and Herzegovina' },
//   { value: 'BW', label: 'Botswana' },
//   { value: 'BR', label: 'Brazil' },
//   { value: 'IO', label: 'British Indian Ocean Territory' },
//   { value: 'BN', label: 'Brunei Darussalam' },
//   { value: 'BG', label: 'Bulgaria' },
//   { value: 'BF', label: 'Burkina Faso' },
//   { value: 'BI', label: 'Burundi' },
//   { value: 'KH', label: 'Cambodia' },
//   { value: 'CM', label: 'Cameroon' },
//   { value: 'CA', label: 'Canada' },
//   { value: 'CV', label: 'Cape Verde' },
//   { value: 'KY', label: 'Cayman Islands' },
//   { value: 'CF', label: 'Central African Republic' },
//   { value: 'TD', label: 'Chad' },
//   { value: 'CL', label: 'Chile' },
//   { value: 'CN', label: 'China' },
//   { value: 'CX', label: 'Christmas Island' },
//   { value: 'CC', label: 'Cocos (Keeling) Islands' },
//   { value: 'CO', label: 'Colombia' },
//   { value: 'KM', label: 'Comoros' },
//   { value: 'CG', label: 'Congo' },
//   { value: 'CD', label: 'Congo, The Democratic Republic of the' },
//   { value: 'CK', label: 'Cook Islands' },
//   { value: 'CR', label: 'Costa Rica' },
//   { value: 'CI', label: "Côte d'Ivoire" },
//   { value: 'HR', label: 'Croatia' },
//   { value: 'CU', label: 'Cuba' },
//   { value: 'CW', label: 'Curaçao' },
//   { value: 'CY', label: 'Cyprus' },
//   { value: 'CZ', label: 'Czech Republic' },
//   { value: 'DK', label: 'Denmark' },
//   { value: 'DJ', label: 'Djibouti' },
//   { value: 'DM', label: 'Dominica' },
//   { value: 'DO', label: 'Dominican Republic' },
//   { value: 'EC', label: 'Ecuador' },
//   { value: 'EG', label: 'Egypt' },
//   { value: 'SV', label: 'El Salvador' },
//   { value: 'GQ', label: 'Equatorial Guinea' },
//   { value: 'ER', label: 'Eritrea' },
//   { value: 'EE', label: 'Estonia' },
//   { value: 'ET', label: 'Ethiopia' },
//   { value: 'FK', label: 'Falkland Islands (Malvinas)' },
//   { value: 'FO', label: 'Faroe Islands' },
//   { value: 'FJ', label: 'Fiji' },
//   { value: 'FI', label: 'Finland' },
//   { value: 'FR', label: 'France' },
//   { value: 'GF', label: 'French Guiana' },
//   { value: 'PF', label: 'French Polynesia' },
//   { value: 'TF', label: 'French Southern Territories' },
//   { value: 'GA', label: 'Gabon' },
//   { value: 'GM', label: 'Gambia' },
//   { value: 'GE', label: 'Georgia' },
//   { value: 'DE', label: 'Germany' },
//   { value: 'GH', label: 'Ghana' },
//   { value: 'GI', label: 'Gibraltar' },
//   { value: 'GR', label: 'Greece' },
//   { value: 'GL', label: 'Greenland' },
//   { value: 'GD', label: 'Grenada' },
//   { value: 'GP', label: 'Guadeloupe' },
//   { value: 'GU', label: 'Guam' },
//   { value: 'GT', label: 'Guatemala' },
//   { value: 'GG', label: 'Guernsey' },
//   { value: 'GN', label: 'Guinea' },
//   { value: 'GW', label: 'Guinea-Bissau' },
//   { value: 'GY', label: 'Guyana' },
//   { value: 'HT', label: 'Haiti' },
//   { value: 'HM', label: 'Heard Island and McDonald Islands' },
//   { value: 'VA', label: 'Holy See (Vatican City State)' },
//   { value: 'HN', label: 'Honduras' },
//   { value: 'HK', label: 'Hong Kong' },
//   { value: 'HU', label: 'Hungary' },
//   { value: 'IS', label: 'Iceland' },
//   { value: 'IN', label: 'India' },
//   { value: 'ID', label: 'Indonesia' },
//   { value: 'XZ', label: 'Installations in International Waters' },
//   { value: 'IR', label: 'Iran, Islamic Republic of' },
//   { value: 'IQ', label: 'Iraq' },
//   { value: 'IE', label: 'Ireland' },
//   { value: 'IM', label: 'Isle of Man' },
//   { value: 'IL', label: 'Israel' },
//   { value: 'IT', label: 'Italy' },
//   { value: 'JM', label: 'Jamaica' },
//   { value: 'JP', label: 'Japan' },
//   { value: 'JE', label: 'Jersey' },
//   { value: 'JO', label: 'Jordan' },
//   { value: 'KZ', label: 'Kazakhstan' },
//   { value: 'KE', label: 'Kenya' },
//   { value: 'KI', label: 'Kiribati' },
//   { value: 'KP', label: "Korea, Democratic People's Republic of" },
//   { value: 'KR', label: 'Korea, Republic of' },
//   { value: 'KW', label: 'Kuwait' },
//   { value: 'KG', label: 'Kyrgyzstan' },
//   { value: 'LA', label: "Lao People's Democratic Republic" },
//   { value: 'LV', label: 'Latvia' },
//   { value: 'LB', label: 'Lebanon' },
//   { value: 'LS', label: 'Lesotho' },
//   { value: 'LR', label: 'Liberia' },
//   { value: 'LY', label: 'Libya' },
//   { value: 'LI', label: 'Liechtenstein' },
//   { value: 'LT', label: 'Lithuania' },
//   { value: 'LU', label: 'Luxembourg' },
//   { value: 'MO', label: 'Macao' },
//   { value: 'MK', label: 'Macedonia, The former Yugoslav Republic of' },
//   { value: 'MG', label: 'Madagascar' },
//   { value: 'MW', label: 'Malawi' },
//   { value: 'MY', label: 'Malaysia' },
//   { value: 'MV', label: 'Maldives' },
//   { value: 'ML', label: 'Mali' },
//   { value: 'MT', label: 'Malta' },
//   { value: 'MH', label: 'Marshall Islands' },
//   { value: 'MQ', label: 'Martinique' },
//   { value: 'MR', label: 'Mauritania' },
//   { value: 'MU', label: 'Mauritius' },
//   { value: 'YT', label: 'Mayotte' },
//   { value: 'MX', label: 'Mexico' },
//   { value: 'FM', label: 'Micronesia, Federated States of' },
//   { value: 'MD', label: 'Moldova, Republic of' },
//   { value: 'MC', label: 'Monaco' },
//   { value: 'MN', label: 'Mongolia' },
//   { value: 'ME', label: 'Montenegro' },
//   { value: 'MS', label: 'Montserrat' },
//   { value: 'MA', label: 'Morocco' },
//   { value: 'MZ', label: 'Mozambique' },
//   { value: 'MM', label: 'Myanmar' },
//   { value: 'NA', label: 'Namibia' },
//   { value: 'NR', label: 'Nauru' },
//   { value: 'NP', label: 'Nepal' },
//   { value: 'NL', label: 'Netherlands' },
//   { value: 'NC', label: 'New Caledonia' },
//   { value: 'NZ', label: 'New Zealand' },
//   { value: 'NI', label: 'Nicaragua' },
//   { value: 'NE', label: 'Niger' },
//   { value: 'NG', label: 'Nigeria' },
//   { value: 'NU', label: 'Niue' },
//   { value: 'NF', label: 'Norfolk Island' },
//   { value: 'MP', label: 'Northern Mariana Islands' },
//   { value: 'NO', label: 'Norway' },
//   { value: 'OM', label: 'Oman' },
//   { value: 'PK', label: 'Pakistan' },
//   { value: 'PW', label: 'Palau' },
//   { value: 'PS', label: 'Palestine, State of' },
//   { value: 'PA', label: 'Panama' },
//   { value: 'PG', label: 'Papua New Guinea' },
//   { value: 'PY', label: 'Paraguay' },
//   { value: 'PE', label: 'Peru' },
//   { value: 'PH', label: 'Philippines' },
//   { value: 'PN', label: 'Pitcairn' },
//   { value: 'PL', label: 'Poland' },
//   { value: 'PT', label: 'Portugal' },
//   { value: 'PR', label: 'Puerto Rico' },
//   { value: 'QA', label: 'Qatar' },
//   { value: 'RE', label: 'Reunion' },
//   { value: 'RO', label: 'Romania' },
//   { value: 'RU', label: 'Russian Federation' },
//   { value: 'RW', label: 'Rwanda' },
//   { value: 'BL', label: 'Saint Barthélemy' },
//   { value: 'SH', label: 'Saint Helena, Ascension and Tristan Da Cunha' },
//   { value: 'KN', label: 'Saint Kitts and Nevis' },
//   { value: 'LC', label: 'Saint Lucia' },
//   { value: 'MF', label: 'Saint Martin (French Part)' },
//   { value: 'PM', label: 'Saint Pierre and Miquelon' },
//   { value: 'VC', label: 'Saint Vincent and the Grenadines' },
//   { value: 'WS', label: 'Samoa' },
//   { value: 'SM', label: 'San Marino' },
//   { value: 'ST', label: 'Sao Tome and Principe' },
//   { value: 'SA', label: 'Saudi Arabia' },
//   { value: 'SN', label: 'Senegal' },
//   { value: 'RS', label: 'Serbia' },
//   { value: 'SC', label: 'Seychelles' },
//   { value: 'SL', label: 'Sierra Leone' },
//   { value: 'SG', label: 'Singapore' },
//   { value: 'SX', label: 'Sint Maarten (Dutch Part)' },
//   { value: 'SK', label: 'Slovakia' },
//   { value: 'SI', label: 'Slovenia' },
//   { value: 'SB', label: 'Solomon Islands' },
//   { value: 'SO', label: 'Somalia' },
//   { value: 'ZA', label: 'South Africa' },
//   { value: 'GS', label: 'South Georgia and the South Sandwich Islands' },
//   { value: 'SS', label: 'South Sudan' },
//   { value: 'ES', label: 'Spain' },
//   { value: 'LK', label: 'Sri Lanka' },
//   { value: 'SD', label: 'Sudan' },
//   { value: 'SR', label: 'Suriname' },
//   { value: 'SJ', label: 'Svalbard and Jan Mayen' },
//   { value: 'SZ', label: 'Swaziland' },
//   { value: 'SE', label: 'Sweden' },
//   { value: 'CH', label: 'Switzerland' },
//   { value: 'SY', label: 'Syrian Arab Republic' },
//   { value: 'TW', label: 'Taiwan, Province of China' },
//   { value: 'TJ', label: 'Tajikistan' },
//   { value: 'TZ', label: 'Tanzania, United Republic of' },
//   { value: 'TH', label: 'Thailand' },
//   { value: 'TL', label: 'Timor-Leste' },
//   { value: 'TG', label: 'Togo' },
//   { value: 'TK', label: 'Tokelau' },
//   { value: 'TO', label: 'Tonga' },
//   { value: 'TT', label: 'Trinidad and Tobago' },
//   { value: 'TN', label: 'Tunisia' },
//   { value: 'TR', label: 'Turkey' },
//   { value: 'TM', label: 'Turkmenistan' },
//   { value: 'TC', label: 'Turks and Caicos Islands' },
//   { value: 'TV', label: 'Tuvalu' },
//   { value: 'UG', label: 'Uganda' },
//   { value: 'UA', label: 'Ukraine' },
//   { value: 'AE', label: 'United Arab Emirates' },
//   { value: 'GB', label: 'United Kingdom' },
//   { value: 'US', label: 'United States' },
//   { value: 'UM', label: 'United States Minor Outlying Islands' },
//   { value: 'UY', label: 'Uruguay' },
//   { value: 'UZ', label: 'Uzbekistan' },
//   { value: 'VU', label: 'Vanuatu' },
//   { value: 'VE', label: 'Venezuela' },
//   { value: 'VN', label: 'Viet Nam' },
//   { value: 'VG', label: 'Virgin Islands, British' },
//   { value: 'VI', label: 'Virgin Islands, U.S.' },
//   { value: 'WF', label: 'Wallis and Futuna' },
//   { value: 'EH', label: 'Western Sahara' },
//   { value: 'YE', label: 'Yemen' },
//   { value: 'ZM', label: 'Zambia' },
//   { value: 'ZW', label: 'Zimbabwe' },
// ];

export const PACKAGE_TYPE_OPTIONS = [
  { value: 'BAGS', label: 'Bags' },
  { value: 'BALES', label: 'Bales' },
  { value: 'BARRELS', label: 'Barrels' },
  { value: 'BOX_PALLETS', label: 'Box Pallets' },
  { value: 'BOXES', label: 'Boxes' },
  { value: 'CARTONS', label: 'Cartons' },
  { value: 'CASES', label: 'Cases' },
  { value: 'CRATES', label: 'Crates' },
  { value: 'DRUMS', label: 'Drums' },
  { value: 'PACKAGES', label: 'Packages' },
  { value: 'PALLETS', label: 'Pallets' },
  { value: 'ROWS', label: 'Rows' },
  { value: 'SKIDS', label: 'Skids' },
];

export const PACKAGE_TYPE_OPTIONS_WITH_CONTAINERS = [
  { value: 'CONTAINERS', label: 'packageTypes.CONTAINERS' },
  ...PACKAGE_TYPE_OPTIONS,
];

export const PACKAGE_TYPE_OPTIONS_CONTAINERS_ONLY = [
  { value: 'CONTAINERS', label: 'packageTypes.CONTAINERS' },
];

export const CONTAINER_TYPE_OPTIONS = [
  { value: '20GP', label: "20' General Purpose" },
  { value: '40GP', label: "40' General Purpose" },
  { value: '40HC', label: "40' High Cube" },
];

export const DIMENSIONS_UOM_OPTIONS = [
  { value: 'CM', label: 'dimensionsUOMs.CM' },
  { value: 'IN', label: 'dimensionsUOMs.IN' },
  { value: 'M', label: 'dimensionsUOMs.M' },
  { value: 'MM', label: 'dimensionsUOMs.MM' },
];

export const WEIGHT_UOM_OPTIONS = [
  { value: 'KG', label: 'weightUOMs.KG' },
  { value: 'LB', label: 'weightUOMs.LB' },
  { value: 'TON', label: 'weightUOMs.TON' },
];

export const CURRENCY_OPTIONS = [
  { value: 'AED', label: 'currencyOptions.AED' },
  { value: 'AFN', label: 'currencyOptions.AFN' },
  { value: 'ALL', label: 'currencyOptions.ALL' },
  { value: 'AMD', label: 'currencyOptions.AMD' },
  { value: 'ANG', label: 'currencyOptions.ANG' },
  { value: 'AOA', label: 'currencyOptions.AOA' },
  { value: 'ARS', label: 'currencyOptions.ARS' },
  { value: 'AUD', label: 'currencyOptions.AUD' },
  { value: 'AWG', label: 'currencyOptions.AWG' },
  { value: 'AZN', label: 'currencyOptions.AZN' },
  { value: 'BAM', label: 'currencyOptions.BAM' },
  { value: 'BBD', label: 'currencyOptions.BBD' },
  { value: 'BDT', label: 'currencyOptions.BDT' },
  { value: 'BGN', label: 'currencyOptions.BGN' },
  { value: 'BHD', label: 'currencyOptions.BHD' },
  { value: 'BIF', label: 'currencyOptions.BIF' },
  { value: 'BMD', label: 'currencyOptions.BMD' },
  { value: 'BND', label: 'currencyOptions.BND' },
  { value: 'BOB', label: 'currencyOptions.BOB' },
  { value: 'BRL', label: 'currencyOptions.BRL' },
  { value: 'BSD', label: 'currencyOptions.BSD' },
  { value: 'BTN', label: 'currencyOptions.BTN' },
  { value: 'BWP', label: 'currencyOptions.BWP' },
  { value: 'BYN', label: 'currencyOptions.BYN' },
  { value: 'BZD', label: 'currencyOptions.BZD' },
  { value: 'CAD', label: 'currencyOptions.CAD' },
  { value: 'CDF', label: 'currencyOptions.CDF' },
  { value: 'CHF', label: 'currencyOptions.CHF' },
  { value: 'CLP', label: 'currencyOptions.CLP' },
  { value: 'CNY', label: 'currencyOptions.CNY' },
  { value: 'COP', label: 'currencyOptions.COP' },
  { value: 'CRC', label: 'currencyOptions.CRC' },
  { value: 'CUC', label: 'currencyOptions.CUC' },
  { value: 'CUP', label: 'currencyOptions.CUP' },
  { value: 'CVE', label: 'currencyOptions.CVE' },
  { value: 'CZK', label: 'currencyOptions.CZK' },
  { value: 'DJF', label: 'currencyOptions.DJF' },
  { value: 'DKK', label: 'currencyOptions.DKK' },
  { value: 'DOP', label: 'currencyOptions.DOP' },
  { value: 'DZD', label: 'currencyOptions.DZD' },
  { value: 'EGP', label: 'currencyOptions.EGP' },
  { value: 'ERN', label: 'currencyOptions.ERN' },
  { value: 'ETB', label: 'currencyOptions.ETB' },
  { value: 'EUR', label: 'currencyOptions.EUR' },
  { value: 'FJD', label: 'currencyOptions.FJD' },
  { value: 'FKP', label: 'currencyOptions.FKP' },
  { value: 'GBP', label: 'currencyOptions.GBP' },
  { value: 'GEL', label: 'currencyOptions.GEL' },
  { value: 'GGP', label: 'currencyOptions.GGP' },
  { value: 'GHS', label: 'currencyOptions.GHS' },
  { value: 'GIP', label: 'currencyOptions.GIP' },
  { value: 'GMD', label: 'currencyOptions.GMD' },
  { value: 'GNF', label: 'currencyOptions.GNF' },
  { value: 'GTQ', label: 'currencyOptions.GTQ' },
  { value: 'GYD', label: 'currencyOptions.GYD' },
  { value: 'HKD', label: 'currencyOptions.HKD' },
  { value: 'HNL', label: 'currencyOptions.HNL' },
  { value: 'HRK', label: 'currencyOptions.HRK' },
  { value: 'HTG', label: 'currencyOptions.HTG' },
  { value: 'HUF', label: 'currencyOptions.HUF' },
  { value: 'IDR', label: 'currencyOptions.IDR' },
  { value: 'ILS', label: 'currencyOptions.ILS' },
  { value: 'IMP', label: 'currencyOptions.IMP' },
  { value: 'INR', label: 'currencyOptions.INR' },
  { value: 'IQD', label: 'currencyOptions.IQD' },
  { value: 'IRR', label: 'currencyOptions.IRR' },
  { value: 'ISK', label: 'currencyOptions.ISK' },
  { value: 'JEP', label: 'currencyOptions.JEP' },
  { value: 'JMD', label: 'currencyOptions.JMD' },
  { value: 'JOD', label: 'currencyOptions.JOD' },
  { value: 'JPY', label: 'currencyOptions.JPY' },
  { value: 'KES', label: 'currencyOptions.KES' },
  { value: 'KGS', label: 'currencyOptions.KGS' },
  { value: 'KHR', label: 'currencyOptions.KHR' },
  { value: 'KMF', label: 'currencyOptions.KMF' },
  { value: 'KPW', label: 'currencyOptions.KPW' },
  { value: 'KRW', label: 'currencyOptions.KRW' },
  { value: 'KWD', label: 'currencyOptions.KWD' },
  { value: 'KYD', label: 'currencyOptions.KYD' },
  { value: 'KZT', label: 'currencyOptions.KZT' },
  { value: 'LAK', label: 'currencyOptions.LAK' },
  { value: 'LBP', label: 'currencyOptions.LBP' },
  { value: 'LKR', label: 'currencyOptions.LKR' },
  { value: 'LRD', label: 'currencyOptions.LRD' },
  { value: 'LSL', label: 'currencyOptions.LSL' },
  { value: 'LYD', label: 'currencyOptions.LYD' },
  { value: 'MAD', label: 'currencyOptions.MAD' },
  { value: 'MDL', label: 'currencyOptions.MDL' },
  { value: 'MGA', label: 'currencyOptions.MGA' },
  { value: 'MKD', label: 'currencyOptions.MKD' },
  { value: 'MMK', label: 'currencyOptions.MMK' },
  { value: 'MNT', label: 'currencyOptions.MNT' },
  { value: 'MOP', label: 'currencyOptions.MOP' },
  { value: 'MRO', label: 'currencyOptions.MRO' },
  { value: 'MUR', label: 'currencyOptions.MUR' },
  { value: 'MVR', label: 'currencyOptions.MVR' },
  { value: 'MWK', label: 'currencyOptions.MWK' },
  { value: 'MXN', label: 'currencyOptions.MXN' },
  { value: 'MYR', label: 'currencyOptions.MYR' },
  { value: 'MZN', label: 'currencyOptions.MZN' },
  { value: 'NAD', label: 'currencyOptions.NAD' },
  { value: 'NGN', label: 'currencyOptions.NGN' },
  { value: 'NIO', label: 'currencyOptions.NIO' },
  { value: 'NOK', label: 'currencyOptions.NOK' },
  { value: 'NPR', label: 'currencyOptions.NPR' },
  { value: 'NZD', label: 'currencyOptions.NZD' },
  { value: 'OMR', label: 'currencyOptions.OMR' },
  { value: 'PAB', label: 'currencyOptions.PAB' },
  { value: 'PEN', label: 'currencyOptions.PEN' },
  { value: 'PGK', label: 'currencyOptions.PGK' },
  { value: 'PHP', label: 'currencyOptions.PHP' },
  { value: 'PKR', label: 'currencyOptions.PKR' },
  { value: 'PLN', label: 'currencyOptions.PLN' },
  { value: 'PYG', label: 'currencyOptions.PYG' },
  { value: 'QAR', label: 'currencyOptions.QAR' },
  { value: 'RON', label: 'currencyOptions.RON' },
  { value: 'RSD', label: 'currencyOptions.RSD' },
  { value: 'RUB', label: 'currencyOptions.RUB' },
  { value: 'RWF', label: 'currencyOptions.RWF' },
  { value: 'SAR', label: 'currencyOptions.SAR' },
  { value: 'SBD', label: 'currencyOptions.SBD' },
  { value: 'SCR', label: 'currencyOptions.SCR' },
  { value: 'SDG', label: 'currencyOptions.SDG' },
  { value: 'SEK', label: 'currencyOptions.SEK' },
  { value: 'SGD', label: 'currencyOptions.SGD' },
  { value: 'SHP', label: 'currencyOptions.SHP' },
  { value: 'SLL', label: 'currencyOptions.SLL' },
  { value: 'SOS', label: 'currencyOptions.SOS' },
  { value: 'SPL', label: 'currencyOptions.SPL' },
  { value: 'SRD', label: 'currencyOptions.SRD' },
  { value: 'STD', label: 'currencyOptions.STD' },
  { value: 'SVC', label: 'currencyOptions.SVC' },
  { value: 'SYP', label: 'currencyOptions.SYP' },
  { value: 'SZL', label: 'currencyOptions.SZL' },
  { value: 'THB', label: 'currencyOptions.THB' },
  { value: 'TJS', label: 'currencyOptions.TJS' },
  { value: 'TMT', label: 'currencyOptions.TMT' },
  { value: 'TMD', label: 'currencyOptions.TND' },
  { value: 'TOP', label: 'currencyOptions.TOP' },
  { value: 'TRY', label: 'currencyOptions.TRY' },
  { value: 'TTD', label: 'currencyOptions.TTD' },
  { value: 'TVD', label: 'currencyOptions.TVD' },
  { value: 'TWD', label: 'currencyOptions.TWD' },
  { value: 'TZS', label: 'currencyOptions.TZS' },
  { value: 'UAH', label: 'currencyOptions.UAH' },
  { value: 'UGX', label: 'currencyOptions.UGX' },
  { value: 'USD', label: 'currencyOptions.USD' },
  { value: 'UYU', label: 'currencyOptions.UYU' },
  { value: 'UZS', label: 'currencyOptions.UZS' },
  { value: 'VEF', label: 'currencyOptions.VEF' },
  { value: 'VND', label: 'currencyOptions.VND' },
  { value: 'VUV', label: 'currencyOptions.VUV' },
  { value: 'WST', label: 'currencyOptions.WST' },
  { value: 'XAF', label: 'currencyOptions.XAF' },
  { value: 'XAG', label: 'currencyOptions.XAG' },
  { value: 'XAU', label: 'currencyOptions.XAU' },
  { value: 'XBT', label: 'currencyOptions.XBT' },
  { value: 'XCD', label: 'currencyOptions.XCD' },
  { value: 'XDR', label: 'currencyOptions.XDR' },
  { value: 'XOF', label: 'currencyOptions.XOF' },
  { value: 'XPD', label: 'currencyOptions.XPD' },
  { value: 'XPF', label: 'currencyOptions.XPF' },
  { value: 'XPT', label: 'currencyOptions.XPT' },
  { value: 'YER', label: 'currencyOptions.YER' },
  { value: 'ZAR', label: 'currencyOptions.ZAR' },
  { value: 'ZMW', label: 'currencyOptions.ZMW' },
  { value: 'ZWD', label: 'currencyOptions.ZWD' },
];
