export const SET_QUOTE_FORM_PROP = 'SET_QUOTE_FORM_PROP';
export const ADD_QUOTE_FORM_CARGO_ROW = 'ADD_QUOTE_FORM_CARGO_ROW';
export const REMOVE_QUOTE_FORM_CARGO_ROW = 'REMOVE_QUOTE_FORM_CARGO_ROW';
export const SET_QUOTE_FORM_CARGO_ROW_PROP = 'SET_QUOTE_FORM_CARGO_ROW_PROP';
export const SET_QUOTE_FORM_IS_CONTAINER_CARGO =
  'SET_QUOTE_FORM_IS_CONTAINER_CARGO';

export const SET_COUPON_CAROUSEL_PROP = 'SET_COUPON_CAROUSEL_PROP';

export const SET_NAV_BAR_PROP = 'SET_NAV_BAR_PROP';

export const SET_VIEW_QUOTES_PROP = 'SET_VIEW_QUOTES_PROP';
