REM Import Port-Map-XX.csv files ***DROP COLLECTION ON FIRST FILE ONLY***
mongoimport --host cluster0-shard-00-00-rdywu.mongodb.net:27017,cluster0-shard-00-01-rdywu.mongodb.net:27017,cluster0-shard-00-02-rdywu.mongodb.net:27017 --authenticationDatabase admin --db rates --ssl --username admin --password Cdjuices1 --collection portMaps --type csv --drop --file ../data/Port-Map-DE.csv --headerline
mongoimport --host cluster0-shard-00-00-rdywu.mongodb.net:27017,cluster0-shard-00-01-rdywu.mongodb.net:27017,cluster0-shard-00-02-rdywu.mongodb.net:27017 --authenticationDatabase admin --db rates --ssl --username admin --password Cdjuices1 --collection portMaps --type csv --file ../data/Port-Map-ES.csv --headerline
mongoimport --host cluster0-shard-00-00-rdywu.mongodb.net:27017,cluster0-shard-00-01-rdywu.mongodb.net:27017,cluster0-shard-00-02-rdywu.mongodb.net:27017 --authenticationDatabase admin --db rates --ssl --username admin --password Cdjuices1 --collection portMaps --type csv --file ../data/Port-Map-FR.csv --headerline
mongoimport --host cluster0-shard-00-00-rdywu.mongodb.net:27017,cluster0-shard-00-01-rdywu.mongodb.net:27017,cluster0-shard-00-02-rdywu.mongodb.net:27017 --authenticationDatabase admin --db rates --ssl --username admin --password Cdjuices1 --collection portMaps --type csv --file ../data/Port-Map-GB.csv --headerline
mongoimport --host cluster0-shard-00-00-rdywu.mongodb.net:27017,cluster0-shard-00-01-rdywu.mongodb.net:27017,cluster0-shard-00-02-rdywu.mongodb.net:27017 --authenticationDatabase admin --db rates --ssl --username admin --password Cdjuices1 --collection portMaps --type csv --file ../data/Port-Map-KW.csv --headerline
mongoimport --host cluster0-shard-00-00-rdywu.mongodb.net:27017,cluster0-shard-00-01-rdywu.mongodb.net:27017,cluster0-shard-00-02-rdywu.mongodb.net:27017 --authenticationDatabase admin --db rates --ssl --username admin --password Cdjuices1 --collection portMaps --type csv --file ../data/Port-Map-NL.csv --headerline
mongoimport --host cluster0-shard-00-00-rdywu.mongodb.net:27017,cluster0-shard-00-01-rdywu.mongodb.net:27017,cluster0-shard-00-02-rdywu.mongodb.net:27017 --authenticationDatabase admin --db rates --ssl --username admin --password Cdjuices1 --collection portMaps --type csv --file ../data/Port-Map-SE.csv --headerline

REM Process data
mongo "mongodb://cluster0-shard-00-00-rdywu.mongodb.net:27017,cluster0-shard-00-01-rdywu.mongodb.net:27017,cluster0-shard-00-02-rdywu.mongodb.net:27017/rates?replicaSet=Cluster0-shard-0" --authenticationDatabase admin --ssl --username admin --password Cdjuices1 populateRateCloud.js